parameters:
  AzureSubscription: ''
  SetEsfaResourceGroupTagsScript: 'https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1'
  PackageFile:  ''
  ArmTemplateFolder: ''
  Location: 'West Europe'
  ArmOutputVariableName: 'ARMOutputs'
  EnvironmentTag: 'DEV/Test'
  ParentBusiness: ''
  ServiceOffering: ''
  ResourceGroup: ''
  DfCDevopsPath: ''
  EnvironmentName: ''
  AppSharedResourceGroup: ''
  appSharedCosmosDBName: ''
  PageRegistrationDirectory: ''
  PageRegistrationPath: ''
  PageRegistrationFile: ''
  AppRegistryApiUrl: ''
  ApimCompositeKey: ''
  AppServiceName: ''
  SharedResourceGroupName: ''
  ApimServiceName: ''
  ApimProductInstanceName: ''
  ApiName: ''
  ApiId: ''
  APIMPolicyPath: ''
  ApimImportScript: ''
  SpecificationPath: ''

jobs:
- deployment: DeployTemplate
  displayName: "Deploy arm templates"
  environment: ${{ parameters.EnvironmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../StepTemplates/deploy-arm-template.yml
          parameters: 
            AzureSubscription: '${{ parameters.AzureSubscription }}'
            DfCDevopsPath: '${{ parameters.DfCDevopsPath }}'
            SetEsfaResourceGroupTagsScript: '${{ parameters.SetEsfaResourceGroupTagsScript }}'
            EnvironmentTag: '${{ parameters.EnvironmentTag }}'
            ParentBusiness: '${{ parameters.ParentBusiness }}'
            ServiceOffering: '${{ parameters.ServiceOffering }}'
            ResourceGroup: '${{ parameters.ResourceGroup }}'
            Location: '${{ parameters.Location }}'
            ArmOutputVariableName: '${{ parameters.ArmOutputVariableName }}'
            ArmTemplateFolder: '${{ parameters.ArmTemplateFolder }}'
            AppSharedResourceGroup: '${{ parameters.AppSharedResourceGroup }}'
            appSharedCosmosDBName: '${{ parameters.appSharedCosmosDBName }}'
