variables:
- name: ReleaseEnvironmentName
  value: PP
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: DfcVisitsTestsBuildId
  value: 1
- name: WebAppPrefix
  value: dfc-pp
- name: aspTier
  value: Standard
- name: aspInstances
  value: 3
- name: aspSize
  value: 1