variables:
- name: ReleaseEnvironmentName
  value: SIT
- name: WebAppPrefix
  value: dfc-sit-api-lmi-transformation
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: lmiTransformationAppDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosJobGroupDbCollectionName
  value: job-groups
- name: cosmosJobGroupTempDbCollectionName
  value: job-groups-temp
- name: cosmosJobGroupDiffDbCollectionName
  value: job-groups-differences
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: SubscriptionSettingsEndpoint
  value: https://$(WebAppPrefix)-fa.azurewebsites.net